spring.application.name=MySafeNet

spring.datasource.url=jdbc:postgresql://localhost:5432/mysafenet
spring.datasource.username=zakiazhari
spring.datasource.password=zaki
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.SQL=DEBUG
