spring.application.name=chatAppBack
# Correct PostgreSQL configuration
#spring.datasource.url=jdbc:postgresql://localhost:5431/chat_db
#spring.datasource.username=zakiazhari
#spring.datasource.password=zaki
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.SQL=DEBUG

# Make sure these properties are added to your existing application.properties file



# Hibernate properties - each on its own line!
spring.jpa.hibernate.ddl-auto=update
#spring.docker.compose.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

